name: Python Build
on: [push]

jobs:
  build-multi-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.9, 3.11, 3.13]
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install pytest rdflib
          pip install .
      - name: Test with pytest
        run: |
          pytest
